/* opxx(a,b) OP##a is the enumerate no of operator b */
#ifdef opxx
	opxx(RET,"return","return %s")
	opxx(NEG,"(-)","-%s")
	opxx(PLUS,"+","%s + %s")
	opxx(MINUS, "-","%s - %s")
	opxx(MULT, "*", "%s * %s")
	opxx(DIV, "/", "%s / %s")
	opxx(MOD, "%", "%s \% %s")
	opxx(ASGN, "=", "%s = %s")
	opxx(EQL, "==", "%s == %s")
	opxx(NEQ, "!=", "%s != %s")
	opxx(LSS, "<", "%s < %s")
	opxx(GEQ, ">=", "%s >= %s")
	opxx(GTR, ">", "%s > %s")
	opxx(LEQ, "<=", "%s <= %s")
	opxx(ANDAND, "&&", "%s && %s")
	opxx(OROR, "||", "%s || %s")
	opxx(NOT, "!", "!%s")
	opxx(AND, "&", "%s & %s")
	opxx(OR, "|", "%s | %s")
	opxx(XOR, "^", "%s ^ %s")
	opxx(LSH, "<<", "%s << %s")
	opxx(RSH, ">>", "%s >> %s")
	opxx(BITNOT, "~", "~%s")
	opxx(INDEX, "[]", "%s[%s]")
	opxx(CALL, "()", "%s(%s)")
	opxx(DEREF, "*", "*%s")
	opxx(ADDRESS, "&", "&%s")
	opxx(REF, "@", "@%s")
	opxx(CAST, "#", "(%s)%s")
	opxx(READ, "Cin>>", "read(%s)")
	opxx(WRITE, "Cout<<", "write(%s)")
	opxx(SIZEOF, "sizeof", "sizeof(%s)")
#endif