/* opxx(a,b) OP##a is the enumerate no of operator b */
#ifdef opxx
	opxx(RET,"return","return %s")
	opxx(NEG,"(-)","-%s")
	opxx(PLUS,"+","%s + %s")
	opxx(MINUS, "-","%s - %s")
	opxx(MULT, "*", "%s * %s")
	opxx(DIV, "/", "%s / %s")
	opxx(MOD, "%", "%s \% %s")
	opxx(ASGN, "=", "%s = %s")
	opxx(EQL, "==", "%s == %s")
	opxx(NEQ, "!=", "%s != %s")
	opxx(LSS, "<", "%s < %s")
	opxx(GEQ, ">=", "%s >= %s")
	opxx(GTR, ">", "%s > %s")
	opxx(LEQ, "<=", "%s <= %s")
	opxx(LOGIC_AND, "&&", "%s && %s")
	opxx(LOGIC_OR, "||", "%s || %s")
	opxx(LOGIC_NOT, "!", "!%s")
	opxx(AND, "&", "%s & %s")
	opxx(OR, "|", "%s | %s")
	opxx(XOR, "^", "%s ^ %s")
	opxx(LSH, "<<", "%s << %s")
	opxx(RSH, ">>", "%s >> %s")
	opxx(NOT, "~", "~%s")
	opxx(INDEX, "[]", "%s[%s]")
	opxx(CALL, "()", "%s(%s)")
	opxx(DEREF, "*", "*%s")
	opxx(ADDRESS, "&", "&%s")
	opxx(REF, "@", "%s")
	opxx(CAST, "cast", "cast<%s>(%s)")
	opxx(READ, "read", "read(%s)")
	opxx(WRITE, "write", "write(%s)")
	opxx(SIZEOF, "sizeof", "sizeof(%s)")
	opxx(PREFIX_SELF_PLUS, "++", "++%s")
	opxx(PREFIX_SELF_MINUS, "--", "--%s")
	opxx(SUFIX_SELF_PLUS, "++", "%s++")
	opxx(SUFIX_SELF_MINUS, "--", "--%s")
	opxx(PLUS_ASGN, "+=", "%s += %s")
	opxx(MINUS_ASGN, "-=", "%s -= %s")
	opxx(MULT_ASGN, "*=", "%s *= %s")
	opxx(DIV_ASGN, "/=", "%s /= %s")
	opxx(MOD_ASGN, "%=", "%s %= %s")
	opxx(AND_ASGN, "&=", "%s &= %s")
	opxx(OR_ASGN, "|=", "%s |= %s")
	opxx(XOR_ASGN, "^=", "%s ^= %s")
	opxx(LSH_ASGN, "<<=", "%s <<= %s")
	opxx(RSH_ASGN, ">>=", "%s >>= %s")
	opxx(LOGIC_AND_ASGN, "&&=", "%s &&= %s")
	opxx(LOGIC_OR_ASGN, "||=", "%s ||= %s")
#endif